<a href="https://colab.research.google.com/github/macarov13/Analitica-de-negocios/blob/main/Reto2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Arboles de Decisión**

**Reto 2**

Maria Antonia Caro V.
0. Cargar las librerias de referencia para el modelo

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#Para no tener que cargar el archivo
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


1. Se procede a la carga de datos del archivo

In [ ]:
nxl='/content/drive/MyDrive/Colab Notebooks/2. BD1_Travel_Data_int.xlsx'
XDB=pd.read_excel(nxl,sheet_name=0)
XDB=XDB.dropna()
XDB.head(100)

#Se procede con la selección de las variables
XD=np.array(XDB[['College', 'FoodSpend', 'Income', 'TravelSpend']]) #Datos entrada
print(XD)
yd=np.array(XDB[['CreditCard']]) #Dato que quiero que el modelo pronostique
print(yd)

num_decimales = 5
# Use np.round to round NumPy arrays
XD_rounded = np.round(XD, num_decimales)
yd_rounded = np.round(yd, num_decimales)

print(XD_rounded)
print(yd_rounded)


[[1.00000e+00 5.47243e+03 4.91500e+04 8.27400e+02]
 [2.00000e+00 9.13073e+03 4.78060e+04 8.63550e+02]
 [2.00000e+00 4.45067e+03 4.60500e+04 1.18005e+03]
 ...
 [2.00000e+00 3.58586e+03 4.22500e+04 2.25195e+03]
 [1.00000e+00 1.83395e+03 6.02480e+04 2.00025e+03]
 [2.00000e+00 6.20597e+03 5.85200e+04 3.66750e+03]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [2

2. Creación del modelo - Decision tree


In [ ]:
mar=DecisionTreeClassifier(criterion='gini', max_depth=4) #4 niveles o variables de entrada
mar.fit(XD,yd)
ydp=mar.predict(XD)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(yd,ydp)
print(cm)

#Evaluamos el modelo
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]

Ex=(VN+VP)/(VN+VP+FN+FP) #Que porcentaje de los datos pronostico correctamente
print("La exactitud alcanzada por el modelo es:", Ex)

Se=VP/(VP+FN) #Que porcentaje de los datos positivos pronosticados correctamente
print("La sensibilidad alcanzada por el modelo es:", Se)

Es=VN/(VN+FP) #Que porcentaje de los datos negativos pronosticados correctamente
print("La especificidad alcanzada por el modelo es:", Es)

#Este modelo tiene preferencia por los pre-negados

[[116  41]
 [ 10 333]]
La exactitud alcanzada por el modelo es: 0.898
La sensibilidad alcanzada por el modelo es: 0.9708454810495627
La especificidad alcanzada por el modelo es: 0.7388535031847133


3. ¿Y, donde esta el arbol?

In [ ]:
#Librerias para graficar el árbol
from sklearn.tree import export_graphviz
from pydotplus import graph_from_dot_data

vs=['College', 'FoodSpend', 'Income', 'TravelSpend'] #Titulos para los nodos
dot_graph=export_graphviz(mar, feature_names=vs)
graph=graph_from_dot_data(dot_graph)
graph.write_png('arbol.png')

True

4. Se procede con el pronostico de los nuevos solicitantes

In [ ]:
XDB2=pd.read_excel(nxl,sheet_name=1)
XDB2=XDB2.dropna() #Elimina celdas vacias
XDB2.head(100)

#Asumiendo 'College' es la cloumna con 'Yes'/'No' values
XDB2['College'] = XDB2['College'].map({'Yes': 1, 'No': 0}) # Convert 'Yes'/'No' to 1/0
print(XDB2)

XD2=np.array(XDB2[['College', 'FoodSpend', 'Income', 'TravelSpend']]) #Datos entrada
print(XD2)

#Pronosticamos la aprobacion
ydp2=mar.predict(XD2)
print(ydp2)

print("La probabilidad de que el primer cliente tenga planes de viajar es de:", np.sum(ydp2))
print("El numero total de datos es:", len(ydp2))
print("La probabilidad de que el segundo cliente tenga planes de viajar es de:", len(ydp2)-np.sum(ydp2))

   College  FoodSpend  Income  TravelSpend
0        0    2892.90   65982       2151.6
1        1    6017.66   53986       2002.5
[[0.00000e+00 2.89290e+03 6.59820e+04 2.15160e+03]
 [1.00000e+00 6.01766e+03 5.39860e+04 2.00250e+03]]
[2 2]
La probabilidad de que el primer cliente tenga planes de viajar es de: 4
El numero total de datos es: 2
La probabilidad de que el segundo cliente tenga planes de viajar es de: -2


**Analisis de resultados**

De acuerdo con la base de datos suministradas y el nodo base del arbol de decision se puede observar un total de 500 datos, divididos 157 Uso de Tarjeta de Crédito y un total de 343 No Uso de Tarjeta de Crédito, esto representa el 31% y el 69% respectivamente. De acuerdo con el pronostico realizado por el modelo, este alcanzó una exactitud cercana al 89,8%, valores que fueron similares a la sensibilidad que mide el comportamiento del modelo frente a los que usan tarjeta de crédito, asi como frente a la especificidad indicador que mide el comportamiento del modelo frente a la clasificacion de los que no usan tarjeta de crédito.

Se destaca la existencia de 3 nodos puros "(0, 108)" en donde deben cumplir con la siguiente regla: SI Income>=59098 AND TravelSpend <=1567.875,"(47,0)" en donde deben cumplir con la siguienteregla: SI FoodSpend>= 4990.73 AND TravelSpend<=1188,
"(0,1)" en donde deben cumplir con la siguienteregla: SI FoodSpend>=4972.55 AND TravelSpend<=1188 AND FoodSpend>=4990.73 AND TravelSpend<=1567.875.

Igualmente, podemos evidenciar que las probabilidades de que el primer cliente tenga planes de viajar es del 40% y que las probabilidades de que el segundo cliente tenga planes de viajar son del -20%
